version: '3.4'

services:
  code_runner-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      CODE_REPO: /sourcecodes
      SLAVE_USER_NAME: runner
      SLAVE_HOST_PYTHON: python-slave
    volumes:
      - ./CompilerContainer/Keys:/keys
      - ./CompilerContainer/SourceCode:/sourcecodes

  python-slave:
    image: python-slave
    build:
      context: ./CompilerContainer
      dockerfile: Python.Dockerfile
    environment:
      USER_NAME: runner
    volumes:
      - ./CompilerContainer/Keys:/config/.ssh
      - ./CompilerContainer/SourceCode:/config/sourcecode
