version: '3.4'

services:
  python-slave:
    image: python-slave
    build:
      context: ./CompilerContainer
      dockerfile: Python.Dockerfile
    environment:
      USER_NAME: runner
    volumes:
      - ./CompilerContainer/Keys:/config/.ssh
      - ./CompilerContainer/SourceCode:/config/sourcecode
    ports:
      - "2222:2222"

  java-slave:
    image: java-slave
    build:
      context: ./CompilerContainer
      dockerfile: Java.Dockerfile
    environment:
      USER_NAME: runner
    volumes:
      - ./CompilerContainer/Keys:/config/.ssh
      - ./CompilerContainer/SourceCode:/config/sourcecode
    ports:
      - "2223:2222"

  gcc-slave:
    image: ghcr.io/untitlecms/gcc-sandbox:v0
    volumes:
      - ./CompilerContainer/Keys/authorized_keys:/config/authorized_keys
      - ./CompilerContainer/SourceCode:/sourcecode
    ports:
      - "2224:2222"

  runner:
    image: ghcr.io/untitlecms/code-runner-service:v0
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    environment: 
      PYTHON_SANDBOX_USER: runner
      PYTHON_SANDBOX_HOST: python-slave
      PYTHON_SANDBOX_PORT: 2222
      PYTHON_SANDBOX_KEY: /keys/id_rsa

      JAVA_SANDBOX_USER: runner
      JAVA_SANDBOX_HOST: java-slave
      JAVA_SANDBOX_PORT: 2222
      JAVA_SANDBOX_KEY: /keys/id_rsa

      GCC_SANDBOX_USER: runner
      GCC_SANDBOX_HOST: gcc-slave 
      GCC_SANDBOX_PORT: 2222
      GCC_SANDBOX_KEY: /keys/id_rsa

      LOCAL_CODE_STORAGE: /sourcecodes

      EXECUTION_QUOTA: 10

    volumes:
      - ./CompilerContainer/Keys:/keys
      - ./CompilerContainer/SourceCode:/sourcecodes
